services:
  - type: web
    name: ea7-mesh-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
<<<<<<< HEAD
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: MQTT_BROKER
        value: mqtt://145.239.69.53:1883
      - key: MQTT_USERNAME
        value: EA7!
      - key: MQTT_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
=======
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000
>>>>>>> 44dd3c0efcbf4e1af28da5490f48213faf5b8bb4
